const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;
const NOT_FOUND_CODE = 404;
const CREATED_CODE = 201;

module.exports = {
  BAD_REQUEST_CODE,
  FORBIDDEN_ERROR,
  CREATED_CODE,
  UNAUTHORIZED_ERROR,
  NOT_FOUND_CODE,
  INTERNAL_SERVER_ERROR,
  CONFLICT_ERROR,
};
